apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-app-config
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: jdbc:mysql://team2-project-db.cne4w2cys26c.ap-northeast-2.rds.amazonaws.com:3306/appdb
