apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: resource-app-secret
spec:
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-2:495599735720:secret:rds!db-3af6352b-e7f0-4fdc-9c52-4910b0dd815c-lMb7qs
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-2:495599735720:secret:rds!db-3af6352b-e7f0-4fdc-9c52-4910b0dd815c-lMb7qs
        property: password
