apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: resource-app-secret
spec:
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: REPLACE_WITH_PROD_RDS_MASTER_SECRET_ARN
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: REPLACE_WITH_PROD_RDS_MASTER_SECRET_ARN
        property: password
