apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-ops-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-ops-test
  template:
    metadata:
      labels:
        app: resource-ops-test
    spec:
      containers:
        - name: team2
          image: team2
          ports:
            - containerPort: 8080
